name: Build SwitchGameDowngrader binary

on:
  push:
    branches: [ main2 ]

    paths:
      - '.github/workflows/rewrite.yml'
      - 'code_templates/**'
      - 'include/**'
      - 'libs/**'
      - 'romfs/**'
      - 'source/**'
      - 'build.sh'
      - 'Makefile'

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkita64

    defaults:
      run:
        shell: bash

    steps:
      - name: Set environment variables
        run: |
          echo "nxdt_commit=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          path: nxdumptool
          submodules: recursive

      - name: Build binary
        working-directory: nxdumptool
        run: |
          make -j8

      - name: Upload NRO artifact
        uses: actions/upload-artifact@v4
        with:
          name: nxdt_rw_poc-${{ env.nxdt_commit }}.nro
          path: nxdumptool/SwitchGameDowngrader.nro
          if-no-files-found: error

      - name: Upload ELF artifact
        uses: actions/upload-artifact@v4
        with:
          name: nxdt_rw_poc-${{ env.nxdt_commit }}.elf
          path: nxdumptool/SwitchGameDowngrader.elf
          if-no-files-found: error

      - name: Upload artifacts to pre-release
        uses: ncipollo/release-action@v1
        with:
          # Only update attachments on "rewrite-prerelease" tag.
          prerelease: True
          tag: "rewrite-prerelease"
          updateOnlyUnreleased: True
          # Remove old artifacts and replace with new ones.
          removeArtifacts: False
          replacesArtifacts: True
          # Update preferences.
          allowUpdates: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          artifacts: "nxdumptool/SwitchGameDowngrader.*"
          #artifacts: "nxdumptool/code_templates/tmp/nxdt_rw_poc.*, nxdumptool/nxdumptool.*"
          token: ${{ secrets.GITHUB_TOKEN }}
