name: Build SwitchGameDowngrader binary

on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkita64

    defaults:
      run:
        shell: bash

    steps:
      - name: Set environment variables
        run: |
          echo "nxdt_commit=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build binary
        run: |
          make -j8

      - name: Upload NRO artifact
        uses: actions/upload-artifact@v4
        with:
          name: nxdt_rw_poc-${{ env.nxdt_commit }}.nro
          path: SwitchGameDowngrader.nro
          if-no-files-found: error

      - name: Upload ELF artifact
        uses: actions/upload-artifact@v4
        with:
          name: nxdt_rw_poc-${{ env.nxdt_commit }}.elf
          path: SwitchGameDowngrader.elf
          if-no-files-found: error

      - name: Upload artifacts to pre-release
        uses: ncipollo/release-action@v1
        with:
          prerelease: True
          tag: ${{ github.ref_name }}
          updateOnlyUnreleased: True
          # Remove old artifacts and replace with new ones.
          removeArtifacts: False
          replacesArtifacts: True
          # Update preferences.
          allowUpdates: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          artifacts: "SwitchGameDowngrader.*"
          token: ${{ secrets.GITHUB_TOKEN }}
